In [1]:
import torch
from IPython import display
from d2l import torch as d2l

batch_size = 128
train_iter, test_iter = d2l.load_data_fashion_mnist(batch_size)

In [2]:
num_inputs = 783
num_outputs = 10

W = torch.normal(0, 0.01,size=(num_inputs, num_outputs),requires_grad=True)
b = torch.zeros(num_inputs,num_outputs,requires_grad=True)
W, b

(tensor([[ 0.0091,  0.0126, -0.0020,  ...,  0.0063,  0.0068, -0.0030],
         [-0.0115, -0.0059,  0.0102,  ...,  0.0121, -0.0046, -0.0088],
         [-0.0052,  0.0063,  0.0054,  ..., -0.0028, -0.0003, -0.0025],
         ...,
         [-0.0031,  0.0030, -0.0043,  ...,  0.0008, -0.0008, -0.0134],
         [ 0.0116, -0.0099,  0.0147,  ...,  0.0020, -0.0254,  0.0011],
         [-0.0105,  0.0031,  0.0035,  ..., -0.0113, -0.0052, -0.0067]],
        requires_grad=True),
 tensor([[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]], requires_grad=True))

In [3]:
X = torch.tensor([[1., 2., 3.], [4., 5., 6.]])
X.sum(0, keepdim=True)  # 按列求和 keepdim表示保持二维特性,否则会降维
X.sum(1, keepdim=True)  # 按行求和

tensor([[ 6.],
        [15.]])

In [4]:
def softmax(X):
    X_exp = torch.exp(X)  # 对输入的X进行e^X操作
    partition = X_exp.sum(1, keepdim=True)
    return X_exp / partition

In [5]:
X = torch.normal(0, 1, size=(2, 5))
X_prob =  softmax(X)
X_prob, X_prob.sum(1)

(tensor([[0.6787, 0.0404, 0.1174, 0.1153, 0.0482],
         [0.0411, 0.5869, 0.0348, 0.0531, 0.2842]]),
 tensor([1.0000, 1.0000]))

In [6]:
def net(X):
    return softmax(torch.matmul(X.reshape((-1, W.shape[0]), W) + b))  # 矩阵乘法

In [7]:
y = torch.tensor([0, 2])
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y_hat[[0, 1], y]

tensor([0.1000, 0.5000])

In [8]:
def cross_entropy(y_hat, y):
    """交叉熵函数作为损失函数进行训练"""
    return - torch.log(y_hat[range(len(y_hat)), y])

cross_entropy(y_hat, y)

tensor([2.3026, 0.6931])

In [ ]:
def accuracy(y_hat, y):
    """计算预测正确的数量"""
    if len(y_hat.shape) > 1 and y_hat.shape[1] > 1:
        y_hat